language: r
cache: packages
sudo: required

# Add libv8 needed for running rgbif (in spocc)
apt_packages:
 - libv8-dev 
 - libmagick++-dev

# Install the suggested packages which
# are needed for the vignette builds
r_packages:
 - knitr
 - testthat
 - gam
 - spocc
 - covr

r_github_packages:
 - rstudio/rmarkdown
 - hadley/pkgdown
 
## After success update the code coverage and deploy the pkgdown to gh-pages
after_success:
 - Rscript -e 'library(covr);codecov()'
 - bash ./.deploy_pkgdown.sh
 
# Warnings don't fail build
warnings_are_errors: false
 
## Email notification if the package pass status changes
notifications:
email:
  recipients:
    - zoonproject@gmail.com
  on_success: change
  on_failure: change
  
## Set up the matrix of different runs
env:
  global:
    - ENCRYPTION_LABEL: "1d00135b7611"
    - COMMIT_AUTHOR_EMAIL: "goldingn35@gmail.com"
  matrix:
    - r: release
      not_cran: true
      r_check_args: "--no-manual"
    - r: release
      not_cran: false
      r_check_args: "--no-manual --as--cran"
    - r: devel
      not_cran: true
      r_check_args: "--no-manual"
    - r: devel
      not_cran: false
      r_check_args: "--no-manual --as--cran"
      
