# basic bits:
language: r
sudo: required

# linux system dependencies for R packages
apt_packages:
 - libv8-dev  # for V8 package, for spocc

r_packages:
 - covr  # for code test coverage stats
 - devtools # for checking

script:
 - Rscript -e 'devtools::check()'

# get code covarage stats for coveralls
after_success:
 - Rscript -e 'covr::coveralls()'

notifications:
  email:
    recipients:
      - zoonproject@gmail.com
    on_success: change
    on_failure: change
