# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  global:
    R_CHECK_ARGS: --no-manual
  
  matrix:
  - NOT_CRAN: true
    R_version: devel

  - NOT_CRAN: false
    R_version: devel

  - NOT_CRAN: true
    R_version: release

  - NOT_CRAN: false
    R_version: release


build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs
  
notifications:
  - provider: Email
    to:
      - tomaug@ceh.ac.uk
    subject: 'r-appveyor build {{status}}'                  # optional
    message: ""    # optional
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
